name: 'BlameGPT'
description: 'Identify the culprit PR for a deploy blocker'
inputs:
  command:
    description: 'Command to run ["blame"]'
    required: true
  issue_id:
    description: 'GitHub issue number to find the culprit PR for.'
    required: true
  blamegpt_api_key:
    description: 'BlameGPT API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run BlameGPT
      run: |
        node dist/index.js \
          --command "${{ inputs.command }}" \
          --issue_id "${{ inputs.issue_id }}" \
          --blamegpt_api_key "${{ inputs.blamegpt_api_key }}"
      shell: bash
