name: 'BlameGPT'
description: 'Identify the culprit PR for a deploy blocker'
icon: 'check-circle'
color: 'purple'
inputs:
  command:
    description: 'Command to run ["blame", "ohmydocs", "review"]'
    required: true
  issue_id:
    description: 'GitHub issue number to find the culprit PR for.'
  pull_request_id:
    description: 'GitHub pull request number to find doc update for.'
    required: true
  blamegpt_api_key:
    description: 'BlameGPT API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run BlameGPT
      run: node "${{ github.action_path }}/dist/index.js"
      shell: bash
      env:
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_ISSUE_ID: ${{ inputs.issue_id }}
        INPUT_PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        INPUT_BLAMEGPT_API_KEY: ${{ inputs.blamegpt_api_key }}
